### ISSUE TITLE
Large repository is causing a Javascript out of heap error

### ISSUE THREAD

**Issue by james-gould** [ivangabriele/vscode-tfs#41]
I'm working within a massive (400,000 file) repository on TFS and the update to 1.14 has made this extension crash VSCode every ~30 seconds. I can generally trigger it if I `Ctrl + Space` to get intellisense, the loading icon on the dropbox menu hangs and then I get the crash. Here's  the stack trace:

> Cannot set property 'resourceStates' of undefined: TypeError: Cannot set property 'resourceStates' of undefined
> at TfvcSCMProvider.onDidModelChange (C:\Users\james.vscode\extensions\ms-vsts.team-1.119.2\out\src\tfvc\tfvcscmprovider.js:128:44)
> at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:55860)
> at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57651)
> at Model. (C:\Users\james.vscode\extensions\ms-vsts.team-1.119.2\out\src\tfvc\scm\model.js:188:31)
> at Generator.next ()
> at fulfilled (C:\Users\james.vscode\extensions\ms-vsts.team-1.119.2\out\src\tfvc\scm\model.js:8:58)

**Comment by james-gould** [comment]
And another when I close the folder for my repo and reopen it:

> Cannot read property 'input' of undefined: TypeError: Cannot read property 'input' of undefined
>     at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:637373
>     at Object.g [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:52764)
>     at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:56329)
>     at n.Class.derive._oncancel._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:58157)
>     at n.Class.derive._oncancel._completed (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:57598)
>     at l (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:61093)
>     at n.Class.derive.join.r.forEach.$.then.o.(anonymous function) (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:61307)
>     at Object.g [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:52764)
>     at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:56836)
>     at n.Class.derive._creator._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:58157)

The last line makes me think it's an Electron bug but I don't have much experience in Electron, if it is I'll move this bug report over there.
